### ISSUE TITLE
Add MarkdownPP artifacts to Pypi

### ISSUE THREAD

**Issue by ncjones** [jreese/markdown-pp#12]
Would be nice to be able to pip install MarkdownPP.

**Comment by jreese** [comment]
Took some time today to clean up much of the codebase for Python 3 support, so I wouldn't feel bad about putting it on PyPI, and ended up doing a PEP8 cleanup and adding very basic linting/testing.

Cut a new release, 1.1, and uploaded a package to PyPI.  Cheers!
