### ISSUE TITLE
!INCLUDE should support a shift parameter

### ISSUE THREAD

**Issue by scls19fr** [jreese/markdown-pp#15]
Hello,

it will be nice if `!INCLUDE` could have a `shift` parameter.

`01.md` looks like

    # Title 1
    ## Title 1.1
    ## Title 1.2
    # Title 2
    ## Title 2.1
    ## Title 2.2

`01_sub.md` looks like

I would like to get a Mardown document like

    # Title 1
    ## Title 1.1
    ## Title 1.2
    # Title 2
    ## Title 2.1
    ## Title 2.2
    ### SubTitle 1
    #### SubTitle 1.1
    #### SubTitle 1.2
    ### SubTitle 2
    #### SubTitle 2.1
    #### SubTitle 2.2

`index.mdpp`

    !INCLUDE "01.md"
    !INCLUDE "01_sub.md", 2

`2` would be this `shift` parameter

What is your opinion about it ?

Kind regards

**Comment by Leockard** [comment]
@scls19fr if there's still interest in this, can you post the example `01_sub.md` file so I can work on a PR? It seems it didn't get included correctly in your original issue. Thanks.

**Comment by scls19fr** [comment]
Hi @Leockard

`01_sub.md` could be

```
# SubTitle 1
## SubTitle 1.1
## SubTitle 1.2
# SubTitle 2
## SubTitle 2.1
## SubTitle 2.2
```

and so 

!INCLUDE "01_sub.md", 2

will create and include

```
### SubTitle 1
#### SubTitle 1.1
#### SubTitle 1.2
### SubTitle 2
#### SubTitle 2.1
#### SubTitle 2.2
```
