### ISSUE TITLE
Directory watching and auto-processing

### ISSUE THREAD

**Issue by kennethkau** [jreese/markdown-pp#18]
Hello,

Would having a watch flag which watches a directory (and subdirectories) and processes any changing .mdpp file be useful?

For example: "markdown-pp -w ." will watch the current directory for any .mdpp file and generate the corresponding markdown file with the same filename but with an .md extension.

Thanks!

**Comment by jreese** [comment]
Could be useful, if you or anyone else is willing to contribute this functionality.
