### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by leotrs** [jreese/markdown-pp#22]
The !INCLUDE functionality is handy but a bit limited. It would be more functional if the Include module received parameters to fill in the file to be included. For example:

File: hello.mdpp
```
!INCLUDE "include.md" {world}
```

File: include.md
```
Hello, {{ arg0 }}!
```

Desired hello.md:
```
Hello, world!
```
----
A hacky alternative would be to use the IncludeURL module to include an address on localhost, listening with a server running Flask, which in turn generates a dynamic markdown file based on the included URL, but that seems like overkill.

I could work on a PR if there is interest in this. It could be part of the Include module, or create a different module with a !TEMPLATE directive or similar.

**Comment by Leockard** [comment]
[Here's](https://github.com/Leockard/markdown-pp/blob/master/MarkdownPP/Modules/Include.py) a MVP.
