### ISSUE TITLE
Recursive call over a directory

### ISSUE THREAD

**Issue by leotrs** [jreese/markdown-pp#24]
I have several `.mdpp` files scattered inside a `content/` directory, and it would be really useful to be able to do something like
```
markdown-pp -r content/
```
and have it run recursively on every `.mdpp` it finds.

I know there's the `-w` flag, but having `markdown-pp` on the background watching every change is not really fitting to my workflow. I would like to control when I generate the `.md` files and would like to be able to do it all at once.

If there's interest, I can prepare a PR promptly.

**Comment by Leockard** [comment]
Will PR as soon as the test branch is merged.
