### ISSUE TITLE
Trailing whitespace when inserting TOC

### ISSUE THREAD

**Issue by leotorr** [jreese/markdown-pp#30]
Is there a reason why whitespace is introduced at the end of every TOC line?

[link](https://github.com/jreese/markdown-pp/blob/master/MarkdownPP/Modules/TableOfContents.py#L150): there are two spaces before the newline.

**Comment by jreese** [comment]
This forces a hard newline (`<br/>`) in the Markdown parser, and is intentional.

**Comment by leotorr** [comment]
That actually makes a lot of sense. The problem was that my text editor deletes trailing whitespace on every line at every save, and it was screwing up some tests.
