### ISSUE TITLE
I can't Install markdown-pp

### ISSUE THREAD

**Issue by tidyjiang8** [jreese/markdown-pp#35]
I'm working on Ubuntu16.04.
I follow the steps:
- Install PIP: `sudo apt-get install python-pip`
- Install MarkdownPP: `pip install MarkdownPP`. 

There is no error information on my screen.
But when I try to use command `markdown-pp`, It tells me `markdown-pp: command not found`

I found there is a MarkdownPP folder: `/home/work/.local/lib/python2.7/site-packages/MarkdownPP`

I know nothing about python and pip. 
Could you tell me why and how to install correctly? 
Thanks.

**Comment by tidyjiang8** [comment]
I remove the folder `/home/work/.local/lib/python2.7/site-packages/MarkdownPP` and using `sudo` to install MarkdownPP， it works now. 

Thanks, anyway.

**Comment by leotrs** [comment]
Good to know you're all setup. Drop by if you need anything.
