### ISSUE TITLE
Is there a way to install Markdown-PP if a linux distribution is not supported by it?

### ISSUE THREAD

**Issue by Cloufish** [jreese/markdown-pp#77]
When installing with:
```pip install Markdown-PP```
I get:

```
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement Markdown-PP (from versions: none)
ERROR: No matching distribution found for Markdown-PP
```
So here's a question, is there a way to install Markdown-PP different way? It's weird that I can't install it now. Couple of weeks later the installation went smoothly.

btw I use arch

**Comment by jreese** [comment]
`pip install markdownpp`, no hypen.
